POST http://localhost:3002/groups/Grupo de ajedrez Italiano/sections
content-type: application/json

{
  "user":{
      "username": "Designer00"
    },
  "section":{
    "type": "title",
    "content": {
      "title": "new Section"
    }
  }
}