PUT http://localhost:3002/groups/Grupo de ajedrez Italiano/sections
content-type: application/json

{
  "user":{
    "username": "Designer00"
  },
  "position": 1,
  "section":{
    "content":{
      "title": "Edited Title"
    }
  }
}