POST http://localhost:3002/api/newReport
content-type: application/json

{
  "reportTdype": "reportUser", 
  "report": {
    "reported": "asdf",
    "reason": "asdfasdf",
    "description": "zxcvzxcv"
  }, 
  "userTdyfpe": "registered"
}